# -*- coding: utf-8 -*-
"""CEAT - preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8V1fP75RkPlzQeeX1JKVH7LO9CprEyi
"""

# ======================== MENTAL‑HEALTH PRE‑PROCESS ========================
import pandas as pd, io, re
from google.colab import files

# ── upload ────────────────────────────────────────────────────────────────
print("🔼  Upload the Mental‑Health file (.csv / .xlsx)")
uploaded = files.upload()
fname    = next(iter(uploaded))

def read_any(b, name):
    return pd.read_csv(io.BytesIO(b)) if re.search(r"\.csv$", name, re.I) else pd.read_excel(io.BytesIO(b))

df = read_any(uploaded[fname], fname)
df.columns = df.columns.str.strip()        # trim whitespace

# ── keep & rename just the 4 shared columns ───────────────────────────────
col_map = {
    "Work Hours per Week":        "working_hours",
    "Screen Time per Day (Hours)": "screen_time_hours",
    "Stress Level":               "stress_level",
    "Sleep Hours":                "sleep_hours",
}
df = df[list(col_map)].rename(columns=col_map)

# optional: convert weekly → daily so it matches the other dataset’s “hours per day”
df["working_hours"] = pd.to_numeric(df["working_hours"], errors="coerce") / 7.0

# ── tidy up stress_level if it’s text (Low / Moderate / High …) ────────────
level_map = {"low": 1, "moderate": 2, "medium": 2, "high": 3, "very high": 4}
df["stress_level"] = (
    pd.to_numeric(df["stress_level"], errors="coerce")   # keep numeric as‑is
      .fillna(df["stress_level"].str.lower().map(level_map))
)

# ── numeric conversion & drop NA rows ──────────────────────────────────────
for c in df.columns:
    df[c] = pd.to_numeric(df[c], errors="coerce")
df.dropna(inplace=True)

# ── save & download ────────────────────────────────────────────────────────
out = "mental_health_preprocessed.xlsx"
df.to_excel(out, index=False)
print(f"✅  Saved {out}  — rows kept: {len(df)}")
files.download(out)

# ========================= REMOTE‑WORK PRE‑PROCESS =========================
import pandas as pd, io, re
from google.colab import files

# ── upload ────────────────────────────────────────────────────────────────
print("🔼  Upload the Remote‑Work file (.csv / .xlsx)")
uploaded = files.upload()
fname    = next(iter(uploaded))

def read_any(b, name):
    return pd.read_csv(io.BytesIO(b)) if re.search(r"\.csv$", name, re.I) else pd.read_excel(io.BytesIO(b))

df = read_any(uploaded[fname], fname)
df.columns = df.columns.str.strip()

# ── keep & rename just the 4 shared columns ───────────────────────────────
col_map = {
    "Daily_Working_Hours": "working_hours",
    "Screen_Time":         "screen_time_hours",
    "Stress_Level":        "stress_level",
    "Sleep_Duration":      "sleep_hours",
}
df = df[list(col_map)].rename(columns=col_map)

# ── numeric conversion & drop NA rows ──────────────────────────────────────
for c in df.columns:
    df[c] = pd.to_numeric(df[c], errors="coerce")
df.dropna(inplace=True)

# ── save & download ────────────────────────────────────────────────────────
out = "remote_work_preprocessed.xlsx"
df.to_excel(out, index=False)
print(f"✅  Saved {out}  — rows kept: {len(df)}")
files.download(out)